### PR TITLE
Resolve ./src as root

### PR DESCRIPTION
**Pull request by jestho**
Meaning anything you put in the `/src` folder can easily be imported.

Eg. importing `/src/foo/bar.js` from `/src/components/lots/of/directories/baz.js`:
instead of writing `import Bar from '../../../../foo/bar';`
you can just write `import Bar from 'foo/bar';`

Good times :tada:

### CODE REVIEW

**Comment by jestho** [comment]
Looks like the tests are failing due to mocha not resolving the correct folders. Do you know how to configure this? Not very familiar with mocha nor testing in general... :)

**Comment by jestho** [comment]
Seems like this is breaking the `npm-install-loader`...

**Comment by satya164** [comment]
You can add it to the fallback array instead of adding as the root. Although I'm not sure if I want this, as it can have a confusing behaviour.

**Comment by satya164** [comment]
BTW we're using ava for testing, not Mocha :)

**Pull request closed without merging**
